### ISSUE TITLE
Unable to install natives with JWS zip files

### ISSUE THREAD

**Issue by AdamKrajcik** [ansible-middleware/jws-ansible-playbook#129]
##### SUMMARY

I wasn't able to install JWS with natives.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
```

##### COLLECTION VERSION

```
1.1.1
```

##### STEPS TO REPRODUCE

```yaml
---

- name: "Install JWS with natives from controller zip files"
  hosts: managed-nodes
  vars:
    tomcat_install_method: rhn_zipfiles
    tomcat_native: True
    jws_version: 5.6.0

    # required
    tomcat_setup: true
  roles:
    - jws
```

##### EXPECTED RESULTS

Playbook pass. Natives installed.

##### ACTUAL RESULTS

```[root@localhost opt]# ll
total 10464
drwxr-xr-x. 3 root   root         79 Jun 21 05:27 jws-5.6
-rw-r-----. 1 tomcat tomcat 10714738 Jun 21 05:27 jws-5.6.0-application-server.zip
```
