### ISSUE TITLE
What is tomcat_setup variable?

### ISSUE THREAD

**Issue by AdamKrajcik** [ansible-middleware/jws-ansible-playbook#138]
##### SUMMARY

What is the usage of tomcat_setup variable? There is no mention of it in the documentation. Why is it needed?

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
```

##### COLLECTION VERSION

```
1.1.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Install Tomcat
  hosts: instance
  vars:
    tomcat_version: 9.0.50
  tasks:
    - name: Import role
      import_role:
        name: "middleware_automation.jws.jws"

```

##### EXPECTED RESULTS

Collection should install Tomcat.

##### ACTUAL RESULTS

```
fatal: [instance]: FAILED! => {"msg": "The conditional check 'tomcat_setup' failed. The error was: error while evaluating conditional (tomcat_setup): 'tomcat_setup' is undefined\n\n
...
```
