### ISSUE TITLE
Unable to install JWS without natives.

### ISSUE THREAD

**Issue by AdamKrajcik** [ansible-middleware/jws-ansible-playbook#140]
##### SUMMARY

I'm unable to install JWS without natives.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/akrajcik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/akrajcik/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

```

##### COLLECTION VERSION

```
1.1.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: "Install JWS without natives."
  hosts: managed-nodes
  vars:
    tomcat_setup: true
    jws_version: "5.6.0"
    tomcat_install_dir: "/opt"
    tomcat_home: "/opt/jws-5.6/tomcat"
    tomcat_zipfile: "jws-5.6.0-application-server.zip"
    tomcat_native: False
    tomcat_native_zipfile: "jws-5.6.0-application-server-RHEL8-x86_64.zip"
  collections:
    - redhat.jws
  roles:
    - jws
```

##### EXPECTED RESULTS

Install JWS without natives

##### ACTUAL RESULTS

```
fatal: [managed-node-one]: FAILED! => {"msg": "The conditional check 'not native_archive_path.stat.exists' failed. The error was: error while evaluating conditional (not native_archive_path.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/home/akrajcik/.ansible/collections/ansible_collections/redhat/jws/roles/jws/tasks/install/local.yml': line 54, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy native archive to target nodes\n  ^ here\n"}
```
