### ISSUE TITLE
Inconsistent deployment of files

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws-ansible-playbook#149]
##### SUMMARY

The collection doesn't have a consistent way of deploying files when configuring JWS.  E.g. keystore to be used with the https connector needs to be present in the target hosts before the jws role is run. On the other hand, tomcat-vault files(vault.keystore, vault.properties, VAULT.DAT) are copied as part of the collection and need to be located on the controller in PWD.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/akrajcik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/akrajcik/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

```

##### COLLECTION VERSION

```
1.1.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Install JWS with ZIPs
  hosts: instance
  vars:
    jws_version: "5.6.0"
    tomcat_install_dir: "/opt"
    tomcat_home: "/opt/jws-{{ ews_version[0:3] }}/tomcat"
    tomcat_zipfile: "jws-{{ ews_version }}-application-server.zip"
    tomcat_listen_https_enabled: True
    tomcat_vault_enabled: True
pre_tasks:
    - name: Copy keystore
      copy:
        src: "../resources/ssl/self_signed/server.jks"
        dest: "/etc/ssl/keystore.jks"  
tasks:
    - name: Import JWS role
      import_role:
        name: "redhat.jws.jws"
```

**Comment by rpelisse** [comment]
Yep (and nice catch). We also need to allow to override "pwd" (I'm currently working on this for the patch part). I'll try to give it a stab in the next days, as I'm poking around this part of the collection anyway.

**Comment by rpelisse** [comment]
I concur.

**Comment by rpelisse** [comment]
Here is the playbook with the recents changes in naming that will be introduced by the next version (1.2.0):
```
---
- name: Install JWS with ZIPs
  hosts: all
  vars:
    jws_version: "5.6.0"
    jws_java_version: 1.8.0
    jws_home: "/opt/jws-{{ jws_version[0:3] }}/tomcat"
    jws_tomcat_vault_enabled: True
    jws_systemd_enabled: True

    jws_tomcat_vault_properties: ./vault_files/vault.properties
    jws_tomcat_vault_data: ./vault_files/VAULT.dat
    jws_tomcat_vault_keystore: ./vault_files/vault.keystore
  collections:
    - redhat.jws
  tasks:
    - name: Import JWS role
      ansible.builtin.include_role:
        name: "jws"
  post_tasks:
    - name: "Deploy testapp"
      ansible.builtin.copy:
        src: ./vault_files/testapp
        dest: "{{ jws_home }}/webapps/"
```

Note: for clarity purpose the tomcat_vault_name variable has been renamed jws_tomcat_vault_keystore variable.
