### ISSUE TITLE
Service patches don't always have base and native zips.

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws-ansible-playbook#151]
##### SUMMARY

Service patches don't always have both base and native zips.  They don't have to have either. The apply patch functionality counts with both of them being present, even if only one is provided. While the example expects jws.rhn_ids['5.6.0'].latest_cp.id to be empty, I can provide example when can that happen, e.g. only natives are rebuild. If natives are missing, the collection tries to download them.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/akrajcik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/akrajcik/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

```

##### COLLECTION VERSION

```
1.1.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Install JWS with ZIPs
  hosts: instance
  vars:
    tomcat_install_method: rhn_zipfiles
    jws_version: "5.6.0"
    tomcat_setup: True
    jws_apply_patches: True
    jws_selinux_enabled: False
  tasks:
    - name: Import JWS role
      import_role:
        name: "redhat.jws.jws"
```
##### ACTUAL RESULTS

```
Patch is not installed when id in main.yml is not set. 
```
