### ISSUE TITLE
Missing dependency when selinux policy is used.

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws-ansible-playbook#160]
##### SUMMARY

I don't think we have mentioned anywhere the dependency on selinux python module on the target host. I'm not sure if it is installed by default or not.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/akrajcik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/akrajcik/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

##### COLLECTION VERSION

```
1.1.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Install JWS with ZIPs
  hosts: instance
  vars:
    tomcat_install_method: rhn_zipfiles
    jws_version: "5.6.0"
    tomcat_setup: True
    jws_selinux_enabled: True # it's True by default
  tasks:
    - name: Import JWS role
      import_role:
        name: "redhat.jws.jws"
```

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'selinux'
fatal: [instance]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (libselinux-python) on instance's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

```
