### ISSUE TITLE
Add a way to deploy your application(s)

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#79]
##### SUMMARY
The playbook currently sets up Tomcat/JWS, but it doesn't have the ability to simply deploy applications to it. Can we add a variable which would allow for one or more war files to be deployed (copied) into the Tomcat webapps directory? We would expect that the user has already built their webapp and are ready to deploy it when they stand up a new instance with Ansible.

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
As you have now played a bit with Ansible, I think it will be easier to explain why we did not went thru with this feature earlier.

So suppose you want to deploy app.war from the internal Maven repo of your organization. Any Ansible users will most likely do the following:
```
- name: Download App
  get_url:
    url: http://maven.repo.internal/app.war
    dest: "{{ tomcat_home }}/webapps/"
```
We could then add this generic code into our playbook and make it available as part of the role which will translate, for the user into this :

```
- name: Deploy App
  include_role:
    name: jws
    tasks_from: deploy_webapp.yml
  vars:
    url: http://maven.repo.internal/app.war
    dest: "{{ tomcat_home }}/webapps/"
```

The added-value of wrapping the "complexity" is limited. Also, we'll need to allow overriding almost all attributes of the get_url in case the user needs to change mode, owner, etc.. On top of this, if the user cannot use an URL to fetch the resources (maybe it's already on the drive), we'll either need to add this use case to our role or the user we'll need to bypass it.

For the sake of completeness, we can add this, but I expect most user will simply never user it.

However, I do think there is aspect of app deployment where we can add value, like maybe providing reusable playbook for driver deployment, which are maybe a bit more involved than just adding the jars in the right place.
