### ISSUE TITLE
rhn_zipfiles can't configure redhat_csp_download

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#88]
##### SUMMARY
The playbook fails when attempting to install JWS by downloading it from RHN. There's no documentation about how to configure a playbook to download from RHN, so I looked into `roles/jws/tasks/install/rhn.yml` and attempted to set the required variables.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
```

##### COLLECTION VERSION

Development build of commit 127406bbed2e525aedf91f1c79c7f86915106cc9.

##### STEPS TO REPRODUCE

Configure a playbook to install JWS using the `rhn_zipfiles` method. Playbook snippet below.
Execute playbook and observe failure.

```yaml
    # Use Case 3 - Using JWS, installed from zipfiles downloaded from RHN (JWS)
    tomcat_install_method: rhn_zipfiles
    jws_version: 5.6.0
    tomcat_home: "{{ tomcat_install_dir }}/jws-{{ jws_version.split('.')[0] }}.{{ jws_version.split('.')[1] }}/tomcat"
    tomcat.rhn.username: username
    tomcat.rhn.password: password
```

##### EXPECTED RESULTS

Successful installation of JWS downloaded from RHN.

##### ACTUAL RESULTS

```
ERROR! Invalid variable name in vars specified for Play: 'tomcat.rhn.username' is not a valid variable name

The error appears to be in '/root/.ansible/collections/ansible_collections/middleware_automation/jws/playbook.yml': line 5, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  vars:
    tomcat_setup: true
    ^ here
```
